# Generated by Django 4.0.2 on 2022-03-28 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=40, verbose_name='Автор')),
                ('сomment_text', models.CharField(max_length=2000, verbose_name='Комментарий')),
                ('date', models.DateField(verbose_name='Опубликован')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.articles', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
